name: Executing a custom script
on: [push]

jobs:
  calling-custom-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Calling script
        run: ./custom-script.sh
      
