name: Executing a custom script
on: [push]

jobs:
  calling-custom-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Grant execution permissions
        run: chmod +x ./custom-script.sh
        
      - name: Calling script
        run: ./custom-script.sh
      
