name: Greeting on env variables
on: [push]

env:
  DAY_OF_WEEK: Moday # Workflow level

jobs:
  greeting-job:
    runs-on: ubuntu-latest
    env:
      greeting: Hello
    steps:
      - name: "Say hello"
        run: echo "$greeting $first_name. Today is $DAY_OF_WEEK"
        env:
          first_name: Mona
