name: CI on Multiple Events

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  hello_world: # Job name
    runs-on: ubuntu-latest
    steps:
      - name: "Echo basic information"
        run: |
          echo "reference: $GITHUB_REF"
          echo "job ID: $GITHUB_JOB"
          echo "action: $GITHUB_ACTION"
          echo "actor: $GITHUB_ACTOR"
