name: Example using secrets
on: [push]

jobs:
  use-secrets-as-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Secrets as variables
        run: |
          echo "API: $API_KEY"
        env:
          API_KEY: ${{ secrets.API_KEY }}
