name: Workflow context
on: [push]

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        run: |
          echo "action ${{ github.action }}"
	        echo "action_ref: $ACTION_REF"
	        echo "action_repository: $ACTION_REPOSITORY"
	        echo "base_ref: ${{ github.base_ref }}"
	        echo "env: ${{ github.env }}"
	      env:
		      ACTION_REF: ${{ github.action_ref }}
		      ACTION_REPOSITORY: ${{ github.action_repository }}
