name: Workflow context
on: [push]
env:
  enviroment_variable: "THIS IS FROM ENVIROMENT"

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        run: |
          echo "action ${{ github.action }}"
          echo "env: ${{ github.env }}"
          echo "ref: ${{ github.ref }}"
          echo "action_ref: $ACTION_REF"
          echo "run_id: $RUN_ID"
          echo "run_number: ${{ github.run_number }}"
          echo "run_attemp: ${{ github.run_attempt }}"
        env:
          ACTION_REF: ${{ github.action_ref }}
          RUN_ID: ${{ github.run_id }}

      - name: Environment variables
        run: |
          # Access to the direct variable
          echo "enviroment_variable: $enviroment_variable"

          # Access throguth env object
          echo "enviroment_variable: ${{ env.enviroment_variable }}"
      
      - name: Job context
        run: |
          echo "container: ${{ job.container }}"
