name: Workflow context
on: [push]

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        run: |
          echo "action ${{ github.action }}"
          echo "env: ${{ github.env }}"
          echo "action_ref: $ACTION_REF"
        env:
          ACTION_REF: ${{ github.action_ref }}
