name: Workflow context
on: [push]

jobs:
  extract-data:
    runs-on: ubuntu-latest
    steps:
      - name: Github context
        run: |
          echo "action ${{ github.action }}"
          echo "env: ${{ github.env }}"
          echo "ref: ${{ github.ref }}"
          echo "action_ref: $ACTION_REF"
          echo "run_id: $RUN_ID"
          echo "run_number: ${{ github.run_number }}"
          echo "run_attemp: ${{ github.run_attempt }}"
        env:
          ACTION_REF: ${{ github.action_ref }}
          RUN_ID: ${{ github.run_id }}
